#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: posts

#+AUTHOR: Tom Purl

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* Katas                                                     :@katas:
** DONE Fizzbuzz Using Robot Framework                      :robot_framework:
   CLOSED: [2019-10-17 Thu 20:51]
   :PROPERTIES:
   :EXPORT_FILE_NAME: fizzbuzz-robot-framework
   :EXPORT_DATE: 2019-10-17
   :EXPORT_HUGO_MENU: :menu "main"
   :END:
*** Overview
    The first thing I always try to do to learn a new language after writing "hello
    world" is implementing [[http://codingdojo.org/kata/FizzBuzz/][fizzbuzz]]. This wasn't true with the Robot Framework, so I
    thought it would be time to give it a try.

*** My Implementation

   #+INCLUDE: "./code/katas/robot-framework/fizzbuzz.robot" src robot

*** Observations

    The first thing I learned from this exercise was how surprisingly difficult it
    was to evaluate the result of an expression. If I was running this in Python I
    would do something like this:

#+BEGIN_SRC python
  for num in range(1, 101):
      if num % 15 == 0:
          print("fizzbuzz")
      elif num % 3 == 0:
          print("fizz")
      elif num % 5 == 0:
          print("buzz")
      else:
          print(num)
#+END_SRC

    I can evaluate the =num % 3= part within the else statement using Python. But
    here’s what I *can’t* do using the Robot Framework:

 
#+BEGIN_SRC robot
  Run keyword if    Is Mod Zero    ${number}    15   Log to Console    FIZZBUZZ
  ...    ELSE IF    Run keyword and return status    Is Mod Zero    ${number}    3     Log to Console    FIZZ
  …
#+END_SRC


    I’m sure *something* like this is possible without creating a temporary variable
    (and evaluating the =Is Mod Zero= 3 times *every time*) but I’m not quite sure
    what it is.

    The second thing I learned was how easy it was to run a Python one-liner from
    Robot. If that didn’t work then I simply didn’t see how I was going to evaluate a
    modulus from Robot without writing a Python module (for a one-liner).
* Braindump                                                      :@braindump:
** DONE Emacs Cheat Sheet                                         :org:emacs:
   CLOSED: [2019-10-17 Thu 20:51]
   :PROPERTIES:
   :EXPORT_FILE_NAME: EmacsCheatSheet
   :EXPORT_DATE: 2019-10-17
   :EXPORT_HUGO_MENU: :menu "braindump"
   :EXPORT_HUGO_SECTION: bd
   :END:
   - State "DONE"       from "TODO"       [2019-10-17 Thu 20:51]
*** Screen navigation

  - Quit
      - =C-x C-c=
  - Move down a screen
      - =C-v=
  - Move up a screen
      - =M-v=
  - forward one char
      - =C-f=
  - backwards one char
      - =C-b=
  - up one line
      - =C-p=
  - down one line
      - =C-n=
  - forward one word
      - =M-f=
  - Backwards one word
      - =M-b=
  - Move to the other window
      - =C-x o=
  - Move forward one page
      -  =C-v=
  - Move backwards one page
      -  =M-v=
  - Reset page around cursor with it at the center.
      -  =C-l=
  - Move forward one word
      -  =M-f=
  - Move backwards one word
      -  =M-b=
  - Move to the beginning of a line.
      -  =C-a=
  - Move to the beginning of a sentence.
      -  =M-a=
  - Move to the end of a line.
      -  =C-e=
  - Move to the end of a sentence.
      -  =M-e=
  - Move to the beginning of the document
      -  =M-<= - Move
      - Please note that you also need to press the shift key since =<= is above
        the =,= key.
  - Move to the end of the document
      -  =M->= - Move
  -  Show only one window
      -  =C-x 1=
  -  Horizontally split the current window
      -  =C-x 2=
  -  Vertically split the current window
      -  =C-x 3=

  Moving around one line at a time:

  #+BEGIN_EXAMPLE
                        Previous line, C-p
                                :
                                :
  Backward, C-b .... Current cursor position .... Forward, C-f
                                :
                                :
                          Next line, C-n
  #+END_EXAMPLE

**** Emulating Vim's "gg top" Mnemonic

  In Vim when you are in normal mode you can jump to the beginning of a
  document by pressing =gg= and the end by pressing =G=. Here are some
  keybindings for Emacs that are similar:

  #+BEGIN_SRC emacs-lisp :exports code

  (global-set-key (kbd "C-x gg") 'beginning-of-buffer)
  (global-set-key (kbd "C-x G")  'end-of-buffer)

  #+END_SRC
 
*** Search

  - Incremental Search
      - =C-s=
      - To find the next match just keep pressing =C-s=

  - =M-x replace-string=
    - Find and replace on every instance of a string from the cursor position to the end of the document.

*** File Management

  - Creating a new file
      - Find it =(C-x C-f)=
      - Type in the location where you want to save it.
  - Saving a file
      - =C-x C-s=

**** Registers

  Registers are good for quickly storing and finding all kinds of things, but I
  mostly use them to open files that I use a lot. For example, I can put the 
  following in my =.emacs= file:

  #+BEGIN_EXAMPLE
      ; Org index
      (set-register ?i (cons 'file "c:/td/gtd/org/index.org"))
      ; .emacs file
      (set-register ?e (cons 'file "~/.emacs"))
  #+END_EXAMPLE

  …and then open the files like this:
 
  =C-x r j i=

  =C-x r j e= 
**** Recovery

  To recover a file, open it and then type =M-x recover-file=.

*** Text Management

**** Misc

  - Auto wrap a line by adding a carriage return
      - Similar to =gqip= in Vim
      - =M-q=
  - Selecting Text
      - Simply go to the beginning, press =C-Space= and then navigate to the end
        position.
      - This is a lot like a visual select in Vim.

**** Copying And Pasting With The Kill Ring

  =<DEL>= in Emacs parlance means "Backspace", not "Delete". For that,
  they use =<DELETE>=.

  - =<DEL>=
    - Delete the character just before the cursor. Using the =<DEL>= key
      does *not* add the text to the kill ring, so avoid it when you can.
  - =C-d=
    -  Delete the next character after the cursor
  - =M-<DEL>=
    - Kill the word immediately before the cursor
  - =M-d=
    - Kill the next word after the cursor
  - =C-k=
    - Kill from the cursor position to end of line
  - =M-k=
    - Kill to the end of the current sentence
  - =C-w=
    - Kill selected text
  - =C-y=
    - Yanks the last text killed. With Emacs, "yank" means "yank it off
      of the kill ring", *not* "cut" like it does in Vim.  If you kill a
      bunch of text repeatedly, then one yank pastes all of that text
      back.
  - =M-y=
    - Allows you to "cycle through" your kill ring. If the text retured
      by C-y isn't what you want, jus type this until you see the text
      you want.


**** CUA Mode

  CUA Mode allows you to use C-c and C-v when you have selected text. Here’s more
  information:

  - http://www.emacswiki.org/emacs/CuaMode

  …and here’s what I added to me .emacs file:

  #+BEGIN_EXAMPLE
      (cua-mode t)
      (setq cua-auto-tabify-recptangles nil) ;; Don't tabify after rectangle commands
      (transient-mark-mode 1) ;; No region when it is not highlighted
      (setq cua-keep-region-after-copy t) ;; Standard Windows behavior
  #+END_EXAMPLE

*** Editing Search Buffers
    One of my favorite features of Emacs is how easy it is to edit the *results* of a
    search buffer. Here's how you do that in different scenarios.
**** Word Search
     TODO
**** File Name Search
     1. First find the files using =find-name-dired=.
     2. Then use =wdired= to edit the results.
*** Scripting

**** Interrogating A Variable VAles

  If you want to find out the current value of a variable, just type the
  following:

  #+BEGIN_EXAMPLE
      C-h v <var name>
  #+END_EXAMPLE

  For example:

  #+BEGIN_EXAMPLE
      C-h v org-agenda-files
  #+END_EXAMPLE

*** Misc

**** Remove Version Page On Startup

  #+BEGIN_EXAMPLE
      ; http://askubuntu.com/a/4824
      (setq inhibit-startup-screen t)
      (add-hook 'emacs-startup-hook
        (lambda () (delete-other-windows)) t)
  #+END_EXAMPLE

**** Change The Default Web Browser

  This is all I had to add to my =.emacs= file on my Windows 7 machine to
  start using Firefox instead of IE:

  #+BEGIN_EXAMPLE
      (setq browse-url-browser-function 'browse-url-firefox)
  #+END_EXAMPLE

**** Show Line Numbers

  #+BEGIN_EXAMPLE
      M-x linum-mode
  #+END_EXAMPLE

**** Toggle Word Wrap

  This is similar to the =:set nowrap= command in Vim, except it toggles
  the option:

  #+BEGIN_EXAMPLE

  M-x toggle-truncate-lines

  #+END_EXAMPLE
** DONE Robot Framework Cheat Sheet                   :emacs:robot_framework:
   :PROPERTIES:
   :EXPORT_FILE_NAME: Robot_Framework_Cheat_Sheet
   :EXPORT_DATE: 2019-10-18
   :EXPORT_HUGO_MENU: :menu "braindump"
   :EXPORT_HUGO_SECTION: bd
   :END:
*** Emacs
     Make sure that you create a ctags/etags file so you can use the [[help:robot-mode-find-kw][robot-mode-find-kw]]
     function to jump to a keyword's definition.

     On windows, I had the best luck with the Universal Ctags executable. Here's the
     command that I use at my project's root to generate my tags file for Emacs:

     #+BEGIN_SRC sh
       cd project-root
       ctags.exe -e --langmap="Robot:.robot.txt" -R
     #+END_SRC
*** Debugging
**** General
     This is an excellent reference:

     - https://docs.plone.org/external/plone.app.robotframework/docs/source/debugging.html
**** Dumping All Variable Values
     Use the following keyword to dump all of the existing variables:

     - =Log Variables    level=INFO=

     Please note that the =level= is VERY important. Just choose INFO and you'll see
     everything you care about.

